spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/g_market_online
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        ddl-auto: update  # create, update, validate, or none
        show_sql: true
        format_sql: true
bucket: /Users/rail/IdeaProjects/SkillSpace_Enterprise/7SpringBootAndData/EmarketSpringBootWeb/src/main/resources/static
